<?php
	return	array (
  'enable_replace_google_cdn' => true,
  'google_fonts_lib' => '1',
  'gravatar-server' => '1',
  'custom-gravatar-server' => '',
  'gravatar-cache-days' => '7',
  'disable-admin-bar' => true,
  'clean-wp-header' => 
  array (
    0 => 'rsd_link',
    1 => 'wlwmanifest_link',
    2 => 'wp_resource_hints',
    3 => 'wp_shortlink_wp_head',
    4 => 'xfn_link',
  ),
  'remove-query-strings' => true,
  'clean-dashboard-widgets' => 
  array (
    0 => 'dashboard_primary',
    1 => 'dashboard_secondary',
    2 => 'dashboard_quick_press',
    3 => 'dashboard_recent_drafts',
  ),
  'remove-default-widgets' => 
  array (
    0 => 'WP_Widget_Meta',
    1 => 'WP_Widget_Media_Audio',
    2 => 'WP_Widget_Media_Video',
    3 => 'WP_Widget_Media_Gallery',
  ),
  'clean-admin-bar' => 
  array (
    0 => 'wp-logo',
  ),
  'remove-wordpress-from-admin-title' => true,
  'custom-wp-footer-text' => '0',
  'footer-text-left' => '',
  'footer-text-right' => '',
  'disable-wp-update' => 
  array (
    0 => 'update_core',
    1 => 'update_plugins',
    2 => 'update_themes',
    3 => 'update_translation',
  ),
  'limit-post-revisions' => '',
  'disable-wp-image-link' => true,
  'disable-wp-browse-happy' => true,
  'remove-wp-emoji' => true,
  'disable-wp-xmlrpc' => true,
  'disable-self-pingback' => true,
  'disable-trackbacks' => true,
  'disable-rest-api' => true,
  'disable-embeds' => true,
  'remove-jquery-migrate' => 
  array (
    0 => 'frontend',
  ),
  'remove-media-element' => true,
  'disable-heartbeat' => 'allow_posts',
  'heartbeat-frequency' => '60',
  'remove-help-tab' => true,
  'disable-file-editor' => true,
  'disable-theme-customizer' => true,
  'remove-theme-menu' => true,
  'remove-plugin-action-links' => true,
  'dashboard-layout' => '2',
  'editor-button-extend' => true,
  'upload-file-rename' => '1',
  'file-rename-mode' => '1',
  'strict-user-register' => true,
  'enhance-user-query' => true,
  'show-user-register-date' => true,
  'show-user-last-login-date' => true,
  'smtp_host' => 'mail.example.com',
  'smtp_port' => '25',
  'smtp_secure' => 'ssl',
  'smtp_auth' => 'yes',
  'smtp_auth_email' => '',
  'smtp_from_name' => '',
  'smtp_from_email' => '',
  'login-with-username-or-email' => true,
  'disable-use-admin-login' => true,
  'disable-share-account' => true,
  'login-redirect-url' => 'http://www.wpbase.com:8083',
  'login-private-Key' => '',
  'login-page-template' => '1',
  'login-background-image' => 'http://www.wpbase.com:8083/wp-content/themes/wpBaseTheme/lib/wp-theme-config/assets/images/parallax1.jpg',
  'login-background-color' => '#f1f1f1',
  'login-logo' => '0',
  'login-logo-image' => 'http://www.wpbase.com:8083/wp-content/themes/wpBaseTheme/lib/wp-theme-config/assets/images/login-logo.png',
  'login-logo-link-url' => 'http://www.wpbase.com:8083',
  'login-logo-title' => '0',
  'login-logo-title-text' => 'wpbase',
  'login-form-info' => '',
  'login-footer-text' => '',
  'pretty-author-url' => 'id',
  'pretty-search-url' => true,
  'enable-maintenance-notice' => true,
  'maintenance-page-title' => '网站维护中',
  'maintenance-subject' => '网站例行维护',
  'maintenance-complete-date' => '',
  'enable-maintenance-autoend' => true,
  'maintenance-content' => '网站临时维护中，请稍后访问，程序员正在疯狂加班！',
  'maintenance-footer' => '',
  'maintenance-ip-whitelist' => '',
  'maintenance-background-color' => '#f1f1f1',
  'maintenance-background' => 
  array (
    'image' => 'http://www.wpbase.com:8083/wp-content/themes/wpBaseTheme/lib/images/bg/parallax4.jpg',
    'repeat' => 'no-repeat',
    'position' => 'center center',
    'attachment' => 'fixed',
    'size' => '',
    'color' => '#f1f1f1',
  ),
  'maintenance-subject-color' => '#ea5504',
  'maintenance-content-color' => '',
  'maintenance-footer-color' => '',
  'maintenance-date-color' => '#ea5504',
  'maintenance-custom-style' => '',
  'import' => '',
  'enable-compress-html' => false,
  'disable-gravatar' => false,
  'footer-load-js' => false,
  'disable-rss-feeds' => false,
  'remove-screen-options-tab' => false,
  'hide-dashboard-menu' => false,
  'list-show-ids' => false,
  'enable_custom_gravatar' => false,
  'show-user-nickname' => false,
  'sort-user-by-post-count' => false,
  'enable_smtp' => false,
  'only-administrator-access-admin' => false,
  'disable-login-error-message' => false,
  'login-encryption' => false,
  'post_name_rewrites' => '',
  'enable_post_name_rewrites' => false,
  'post_id_rewrites' => '',
  'enable_post_id_rewrites' => false,
  'maintenance-mode' => false,
  'enable-maintenance-social' => false,
);